coopnorge/engineering-docker-images

- images/devtools-terraform-v1beta1/context/Dockerfile
https://github.com/coopnorge/engineering-docker-images/issues/40
> add git to tf image

- images/devtools-golang-v1beta1/context/Dockerfile
- images/devtools-golang-v1beta1/context/maker
- images/devtools-golang-v1beta1/tests/test_image.py
- images/devtools-kubernetes-v1beta1/context/Dockerfile
- images/devtools-kubernetes-v1beta1/context/maker
- images/devtools-kubernetes-v1beta1/tests/test_image.py
- images/devtools-terraform-v1beta1/context/maker
- images/devtools-terraform-v1beta1/tests/test_image.py
This makes it posssible to invoke the makefiles directly with no
predefined target.
> Change the maker command to be independently invokeable

- images/devtools-terraform-v1beta1/context/Makefile
implements https://github.com/coopnorge/engineering-docker-images/issues/94
> use terraform bundled with image by default and make tfswitch optional

- images/devtools-terraform-v1beta1/README.md
- images/devtools-terraform-v1beta1/context/Dockerfile
- images/devtools-terraform-v1beta1/context/Makefile
- images/devtools-terraform-v1beta1/context/README.md
Fixes https://github.com/coopnorge/engineering-docker-images/issues/118
> Terraform: lock providers on multiple platforms after initializing/upgrading

- .github/workflows/pr.yaml
- Makefile
- pyproject.toml
Add python validation to CI.
Other changes:
- Fix mypy python version spec to not be a float but a string
- Fix version constraints so poetry update becomes more useful
- Output diff when running lint checks
> Validate python code in CI

- .github/workflows/pr.yaml
- README.md
- images/devtools-golang-v1beta1/context/Makefile
- images/devtools-golang-v1beta1/tests/prototype/README.md
- images/devtools-golang-v1beta1/tests/test_image.py
- images/devtools-kubernetes-v1beta1/context/README.md
- images/devtools-kubernetes-v1beta1/tests/prototype/README.md
- images/devtools-kubernetes-v1beta1/tests/test_image.py
- images/devtools-terraform-v1beta1/context/README.md
- images/devtools-terraform-v1beta1/tests/prototype/README.md
- images/devtools-terraform-v1beta1/tests/test_image.py
closes https://github.com/coopnorge/engineering-docker-images/issues/31
> Use `docker compose` instead of `docker-compose`.

- .github/workflows/pr.yaml
- poetry.lock
Also run poetry install with verbose mode.
> Upgrade poetry dependencies

- .github/workflows/pr.yaml
This reverts commit 6a8f4ba57a6fcde459b981155a466d02719fa7c3.
The implementation still needs some tuning
> Revert "Run builds in parallel (#344)"

- images/techdocs/context/Dockerfile
- images/techdocs/context/docker-lock.json
- images/techdocs/tests/test_image.py
Closes: coopnorge/backstage#229
> Add vale to TechDocs image

- images/techdocs/.gitignore
- images/techdocs/README.md
- images/techdocs/context/Dockerfile
- images/techdocs/context/Makefile
- images/techdocs/context/maker
- images/techdocs/tests/prototype/.markdownlint.yaml
- images/techdocs/tests/prototype/.vale.ini
- images/techdocs/tests/prototype/README.md
- images/techdocs/tests/prototype/catalog-info.yaml
- images/techdocs/tests/prototype/docs/index.md
- images/techdocs/tests/prototype/mkdocs.yml
- images/techdocs/tests/test_image.py
Closes: coopnorge/github-workflow-techdocs#31
> Use make as a task runner

- images/techdocs/context/Makefile
- images/techdocs/context/mkdocs.yml
Merged the files in the wrong order. Caused the baseline to override the
specific file.
> Fix mkdocs.yml merge

- images/techdocs/context/Makefile
- images/techdocs/tests/test_image.py
Closes: coopnorge/coop-playbook#936
> Set default values for TechDocs image validate

- images/techdocs/context/Makefile
[Simply Expanded Variable Assignment][1] does the job, no need for
[Recursively Expanded Variable Assignment][2]
[1]: https://www.gnu.org/software/make/manual/make.html#Simple-Assignment
[2]: https://www.gnu.org/software/make/manual/make.html#Recursive-Assignment
> Use Simply expanded variables

- images/techdocs/context/Makefile
The output is just noise in to CI logs
> Remove output of markdownlint.yaml content

- images/techdocs/context/Dockerfile
- images/techdocs/context/docker-compose.yaml
- images/techdocs/tests/test_image.py
Build the image in a temp directory
Closes: #700
> Mount the repository in the workspace directory

- images/devtools-golang-v1beta1/context/Dockerfile
> Set /src/workspace as a trusted git directory

- images/devtools-golang-v1beta1/context/Dockerfile
- images/devtools-kubernetes-v1beta1/context/Dockerfile
- images/devtools-terraform-v1beta1/context/Dockerfile
- images/poetry-python3.10/context/Dockerfile
- images/poetry-python3.11/context/Dockerfile
- images/poetry-python3.8/context/Dockerfile
- images/poetry-python3.9/context/Dockerfile
- images/techdocs/context/Dockerfile
`safe.directory` has to be set at system level so that user settings
does not overwrite them.
Closes: #720
> Set `/srv/workspace` as a git safe directory

- images/techdocs/context/mkdocs.yml
- images/techdocs/context/requirements-techdocs.in
- images/techdocs/context/requirements-techdocs.txt
- images/techdocs/tests/prototype/docs/data.csv
- images/techdocs/tests/prototype/docs/index.md
Using: https://timvink.github.io/mkdocs-table-reader-plugin/#documentation
> Add support for rendering data tables from files

- docs/images/techdocs.md
> Make it easier to write documentation

- images/devtools-golang-v1beta1/context/go.mod
- images/devtools-golang-v1beta1/context/go.sum
Several of our repositories uses gomockhandler, bundling the tools with
our devtools will make things easier for engineers
> Install gomockhandler

- images/devtools-golang-v1beta1/context/go.mod
- images/devtools-golang-v1beta1/context/go.sum
This reverts commit 3043bae0b64c456128da8c6d79f4bd6bb730fec5.
> Revert "Install gomockhandler (#1351)"

- images/techdocs/context/Dockerfile
fixes https://github.com/coopnorge/engineering-docker-images/issues/1536
> fix: Change openjdk version to one that is available

- images/devtools-terraform-v1beta1/context/Dockerfile
- images/devtools-terraform-v1beta1/context/Makefile
Trying to fix: https://github.com/coopnorge/cloud-platform-team/issues/919
> build(deps): Update terraform-docs version from 0.16.0 to 0.17.0

- images/devtools-kubernetes-v1beta1/context/magefiles/go.mod
- images/devtools-kubernetes-v1beta1/context/magefiles/go.sum
> chore: Update version of mage-kubernetes-lib

- images/devtools-terraform-v1beta1/context/Makefile
We have been having a lot of issues with trivy. Apparently, this workaround works: https://github.com/aquasecurity/trivy/discussions/7668#discussioncomment-11028887
> chore: Use workaround for trivy TOOMANYREQUESTS issue

- images/devtools-terraform-v1beta1/context/Dockerfile
- images/devtools-terraform-v1beta1/context/Makefile
- images/devtools-terraform-v1beta1/tests/test_image.py
Also,
* try to update the db before trivy checks
* enable caching by providing cache directory
ref: https://github.com/coopnorge/cloud-platform-team/issues/997
> feat: Include trivy checks db in the image

- images/devtools-kubernetes-v1beta1/context/magefiles/go.mod
- images/devtools-kubernetes-v1beta1/context/magefiles/go.sum
Reverts coopnorge/engineering-docker-images#2338
> Revert "build(deps): bump github.com/coopnorge/mage-kubernetes-lib from 0.6.0 to 0.7.0 in /images/devtools-kubernetes-v1beta1/context/magefiles"

- images/devtools-golang-v1beta1/context/go.mod
- images/devtools-golang-v1beta1/tests/prototype/go.mod
- images/devtools-kubernetes-v1beta1/context/go.mod
- images/devtools-kubernetes-v1beta1/context/magefiles/go.mod
Ref:
- https://github.com/coopnorge/engineering-issues/issues/439
> chore(deps): Bump Go to 1.23

- .github/dependabot.yml
- images/devtools-terraform-v1beta1/context/Dockerfile
latest version is causing issues
> chore: revert terraform to max allowed version

- .github/workflows/pr.yaml
> chore: Correct name of step for policy-bot validation check
