.github/dependabot.yml

I don't think dependabot runs recursively, trying this to make it work.
Also:
- Update docker image versions with docker-lock

Tell dependabot to work specifically in image directories

---

.hadolint.yaml
images/devtools-golang-v1beta1/context/Dockerfile
images/devtools-terraform-v1beta1/context/Dockerfile

Pinning them does not work with dependabot, so removing the pinning and
ignoring unpinned version warning from hadolint.

Unpin OS package versions in Dockerfiles

---

README.md
images/devtools-terraform-v1beta1/context/Dockerfile
images/devtools-terraform-v1beta1/context/Makefile
images/devtools-terraform-v1beta1/tests/README.md
images/devtools-terraform-v1beta1/tests/prototype/eg_module/main.tf
images/devtools-terraform-v1beta1/tests/prototype/example/example.tf
images/devtools-terraform-v1beta1/tests/prototype/examples/examples.tf
images/devtools-terraform-v1beta1/tests/prototype/main.tf
images/devtools-terraform-v1beta1/tests/prototype/use_eg_module.tf
images/devtools-terraform-v1beta1/tests/run
images/devtools-terraform-v1beta1/tests/test_image.py
mypy.ini
pyproject.toml

Simplify terraform detect and fallback to current directory
The terraform directory detection was trying to be a bit too clever and
ended up missing a bunch of things. This simplifies terraform detection
by just checking for all directories that contain *.tf files, and if
none is found falling back to `.`.
Also:
- added a countermeasure for for potentially interactive tfswitch:
- https://github.com/warrensbox/terraform-switcher/issues/165
- added TFDIRS_EXCLUDE and TFDIRS which users can use to control the
directories that will be considered terraform directories.
Fixes https://github.com/coopnorge/engineering-docker-images/issues/60

Simplify terraform detect and fallback to current directory

---

README.md
images/devtools-terraform-v1beta1/README.md
images/devtools-terraform-v1beta1/context/Makefile
images/devtools-terraform-v1beta1/tests/test_image.py

This is so we can ignore https://github.com/coopnorge/cloud-projects/tree/main/teams
as tfsec is incredibly slow on this module.
More info can be seen in the README.

Add support for `.tfsec-ignore`

---

images/devtools-terraform-v1beta1/context/Makefile

In regards to [this PR](https://github.com/coopnorge/cloud-projects/pull/392): the workflow seems to fail because it's running on an older version of Terraform compared to the workspace itself. `engineering-docker-images`'s TF image does use `terraform-switcher` to select the correct version of Terraform most of the time, [but seemingly not on initial terraform init](https://github.com/coopnorge/engineering-docker-images/blob/main/images/devtools-terraform-v1beta1/context/Makefile#L56), and from what I can tell, [that is the step that fails](https://github.com/coopnorge/cloud-projects/runs/6108948796?check_suite_focus=true).
As such, we need to invoke `terraform-switch` before the initialization steps as well.
@aucampia 
Is this a sensible way to solve this issue?

tfswitch before initializing terraform in terraform image

---

images/devtools-terraform-v1beta1/context/Dockerfile
images/devtools-terraform-v1beta1/context/Makefile
images/devtools-terraform-v1beta1/context/docker-compose.yaml
images/devtools-terraform-v1beta1/tests/README.md
images/devtools-terraform-v1beta1/tests/prototype/.gitignore
images/devtools-terraform-v1beta1/tests/prototype/README.md
images/devtools-terraform-v1beta1/tests/prototype/docker-compose.yaml
images/devtools-terraform-v1beta1/tests/prototype/versions.tf
images/devtools-terraform-v1beta1/tests/test_image.py

Stuff that goes into .terraform is arch and OS dependent so it is best
that this directory not be shared between host and guest, however if
you mounted a volume to `.terraform` then the Makefile did not do
terraform initialization.
This patch changes the Makefile to also check for
`.terraform/providers` and do initialization if it does not exist.
This should work in all cases where there at least one provider.
Also:
- Simplified the testing of the terraform image
- Enable terraform caching and test with and without caching

Make terraform devtools work with `.terraform` as a volume

---

Makefile

Blocked by https://github.com/coopnorge/engineering-docker-images/issues/201

Don't run `validate-images-digests`. 

---

.github/dependabot.yml
README.md
images/benthos-v4/README.md
images/benthos-v4/context/Dockerfile
images/benthos-v4/context/docker-compose.yaml
images/benthos-v4/tests/README.md
images/benthos-v4/tests/run
images/benthos-v4/tests/test_image.py
images/poetry-python3.10/tests/README.md
images/poetry-python3.10/tests/test_image.py
images/poetry-python3.8/tests/test_image.py
images/poetry-python3.9/tests/test_image.py
pyproject.toml

The image is a verbatim copy.
This is so that benthos is available on a google registry
where it can easily be used with Cloud Run.

Add benthos image

---

Dockerfile

This reverts commit 23751fc40b42072642dbf3d1844747153e12d80e.
Reverting as it is a beta

Revert "Bump library/python from 3.10.5 to 3.11.0b5 (#230)"

---

images/poetry-python3.10/tests/test_image.py
images/poetry-python3.8/tests/test_image.py
images/poetry-python3.9/tests/test_image.py

So, we can merge Dependabot PRs if the update is minor.

Use `startsWith` for `poetry-python3.*` images.

---

images/devtools-terraform-v1beta1/context/Makefile

Init args were not passed, so running a reinit causes issues if initial init was with different args

also pass init args to other init commands

---

.github/dependabot.yml

Dependabot config pointed to the wrong path

Fix Dependabot config for TechDocs image

---

.github/dependabot.yml

Updates in terraform tooling from time to time creates a lot of work without providing much value.

Only montly toolchain update for terraform

---

images/techdocs/.gitignore
images/techdocs/context/Makefile
images/techdocs/context/mkdocs.yml
images/techdocs/tests/prototype/mkdocs.yml

Reading the site name from `catalog-info.yaml` removes the need to
provide a `mkdocs.yml`.

Read Site name from catalog-info.yaml

---

images/techdocs/context/Makefile
images/techdocs/tests/prototype/catalog-info.yaml

Closes #456.
I don't think it's actually possible to test this change as the Python tests seem to test the image, and the change is in the `Makefile`. Regardless I added the `SITE_NAME` value to the test, as this is how the value should be presented by the Makefile.
This will be tested at least when the `storm-121` CI runs and picks up this new image.

Add quotes around SITE_NAME in techdocs image

---

images/techdocs/README.md
images/techdocs/context/Dockerfile
images/techdocs/context/Makefile
images/techdocs/context/package-lock.json
images/techdocs/context/package.json

Use `docker compose up techdocs` to run the TechDocs preview site. The
reason for this is that `docker compose run` cannot expose ports.
TechDocs is downgraded due to a bug in 1.2.1 and 1.2.2 that breaks the
preview site.
Closes: #465, closes: #468, closes: coopnorge/coop-playbook#834

Add local preview to TechDocs image

---

images/techdocs/context/Makefile
images/techdocs/tests/test_image.py

`lint` and `linguistics-check` now uses the same input `MARKDOWN_FILES`
to set the files to check. This reduces the cognitive load on the users
of the TechDocs image.

Unify the input to validate sub-targets

---

images/poetry-python3.10/tests/test_image.py
images/poetry-python3.11/tests/test_image.py
images/poetry-python3.8/tests/test_image.py
images/poetry-python3.9/tests/test_image.py
images/techdocs/tests/test_image.py

Hardcoding docker host breaks things for people who use rootless docker
on Linux.
- Fixes https://github.com/coopnorge/engineering-docker-images/issues/520

Don't hardcode docker host

---

images/techdocs/context/Dockerfile
images/techdocs/context/Makefile
images/techdocs/context/README.md
images/techdocs/context/docker-compose.yaml
images/techdocs/tests/README.md
images/techdocs/tests/test_image.py

This is so that it is easier to fix auto-fixable validation errors.
We had this before for the playbook but sadly it was lost when we moved
to backstage.
- Fixes https://github.com/coopnorge/engineering-docker-images/issues/519

Add validate-fix target for techdocs

---

images/techdocs/.gitignore
images/techdocs/context/Dockerfile
images/techdocs/context/Makefile
images/techdocs/tests/prototype/.vale.ini
images/techdocs/tests/test_image.py

To enable usage of our Coop Vale Package we need to be able to download
the package before running vale.

Add support for downloading vale packages

---

images/techdocs/context/requirements-techdocs.in
images/techdocs/context/requirements-techdocs.txt

This reverts commit 2b1089e26edef5350c7b5c37ec24b0278f2ca6a2.
mkdocs-glightbox 0.3.1 has a new hash, this blocks us from updating any
other dependencies in the docker image.

Revert "Bump mkdocs-glightbox from 0.3.0 to 0.3.1 in /images/techdocs/context (#530)"

---

images/devtools-golang-v1beta1/context/Dockerfile.app

When building a container image using the devtools-golang-v1beta1
hadolint complains about unpinned versions. If we do not want to pin the
version of this dependency we need to disable the rule for this specific
line.
Closes: #641

Disable version pinning for hadolint for tzdata

---

images/devtools-golang-v1beta1/context/Dockerfile.app

RTFM... using old issues as docs is not good, test would be good to.
`ignore` is the right way to turn off a rule, not `disable`.
Closes: #641

Ignore version pinning for hadolint for tzdata

---

images/devtools-golang-v1beta1/context/Makefile

To easily be able to pin an OCI to a specific version we need the output
from the OCI build.
For more information see: https://github.com/moby/buildkit#metadata

Output the OCI metedata to a JSON file.

---

docker-lock.json
images/devtools-golang-v1beta1/context/Dockerfile

Dependabot is stuck on this dependency, bumping manually

Bump moby/buildkit from buildkit:v0.10.6-rootless to v0.11.3-rootless in /images/devtools-golang-v1beta1/context

---

docker-lock.json
images/devtools-golang-v1beta1/context/Dockerfile

Dependabot is stuck on this dependency, bumping manually

Bump golangci/golangci-lint from v1.50.0-alpine to v1.51.0-alpine in /images/devtools-golang-v1beta1/context

---

images/devtools-golang-v1beta1/context/.golangci.yml
images/devtools-golang-v1beta1/tests/test_image.py

`deadcode`, `varcheck` and `structcheck` are deprecated and replaced by
`unused`.
Here is the output for the build logs
```console
level=warning msg="[runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused."
level=warning msg="[runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused."
level=warning msg="[runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused."
```

Remove deprecated linters

---

docker-lock.json
images/devtools-golang-v1beta1/context/Dockerfile

Dependabot is stuck on this dependency, bumping manually

Bump bufbuild/buf from 1.12.0 to 1.12.0 in /images/devtools-golang-v1beta1/context

---

images/techdocs/context/Makefile
images/techdocs/tests/prototype/catalog-info.yaml

If there are multiple objects in `catalog-info.yaml`, pick the first one
to build the metadata. We current only support TechDocs for 1 Backstage
entity per repository.

Select the first yaml object to create metadata

---

.github/workflows/pr.yaml

To fix the warning: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Use `$GITHUB_OUTPUT` instead of `set-output`

---

.github/workflows/pr.yaml

CI was not built initially to remove the images.
This change came from removing poetry-python3.8 image.
Since this image has been remove, we revert the change for the CI.

Remove `added|modified` from paths filter

---

images/techdocs/context/Dockerfile

Java had some dependencies that could not be installed, declaring them
manually.

Fix java install

---

images/devtools-golang-v1beta1/context/.golangci.yml

Increasing timeout for golangci-lint as I experience timeouts quite often. default is 1m, setting it to 5m.
I don't know if this should be passed as a optional flag in the Makefile instead, and value set by environment variable if set.
That way users of the docker-image can set their own timeout value.
But I think having 5m as a default value for us is also OK.

increase timeout for golangci-lint

---

images/techdocs/context/markdownlint.yaml

We use tabs in our Golang code, as such it should be possible to use
tabs when writing examples.

Add support for hard tabs in code blocks

---

docs/images/devtools-golang-v1beta1.md
images/devtools-golang-v1beta1/context/Dockerfile

To install and update our private Go modules from
https://github.com/coopnorge both `git` and `go` must be configured
property.
Since this configuration rarely changes and is not user specific adding
this configuration to the devtools provides for a much improved
developer experience.
Closes: #1221

Make installing & updating private Go modules easy

---

docs/images/devtools-golang-v1beta1.md
images/devtools-golang-v1beta1/context/Dockerfile

When using devtools-golang-v1beta1 in GitHub actions GitHub we are
currently not able to override the system wide configuration.
This means that the git configuration for accessing private Go modules
must be defined outside of the image.
This partially reverts 5af42d88508fa7f3245c5516e2e6eac1ace3d6d7

Revert git config for private Go modules

---

.github/workflows/pr.yaml

Most of our references to external GitHub Actions only reference the
major versions. We had a few that referenced the full SemVer, this
caused a lot of pull requests and work.

Reduce the amount of PRs to update GitHub Actions

---

images/devtools-golang-v1beta1/context/Dockerfile
images/devtools-golang-v1beta1/context/go.mod
images/devtools-golang-v1beta1/context/go.sum
images/devtools-golang-v1beta1/context/tools.go
images/devtools-golang-v1beta1/tests/test_image.py

Several of our repositories uses gomockhandler, bundling the tools with
our devtools will make things easier for engineers.

Install `gomockhandler`

---

.github/workflows/pr.yaml

[See](https://github.com/coopnorge/engineering-docker-images/actions/runs/7004437459) for failing build.
Techdocs now requires read permission on pull-request.
[See](https://github.com/coopnorge/github-workflow-techdocs/blob/v0/.github/workflows/techdocs.yaml#L36)

fix: techdocs now requires additional permission

---

images/devtools-python3.10-v1beta1/context/Dockerfile

The re-usable workflow we use for building and validating oci,
[see](https://github.com/coopnorge/github-workflow-devtools-build-oci/blob/main/.github/workflows/oci-ci.yaml#L97)
expects yq binary to be there to get image name from oci-metadata.

chore: adding missing yq binary to python3.10 devtools

---

images/devtools-python3.10-v1beta1/context/Dockerfile.app

As one of the built image in artifact registry showed that it has
17 critical vulnerability, manually updating it.

chore: update python base image used by built image

---

.github/dependabot.yml

[See](https://github.com/coopnorge/engineering-docker-images/pull/1487#pullrequestreview-1761903094)
for the review that suggested adding this change.

deps: added python3.10 devtols to dependabot config

---

images/devtools-python3.10-v1beta1/context/Makefile

Currently, python3.10 devtools expects `py_source` to be `.src` and
`.tests`.
However, when trying to use the devtools with other project, we noticed
that not all systems use the same project structure.
This change will allow us to set the py_source variable either via
env or commandline argument.

feat: python3.10 devtools, allow setting python source directory

---

.policy.yml

CI can't be required using Policy Bot. Combining GitHub status checks
and Policy Bot for approvals solves the problem.
Depends on:
- https://github.com/coopnorge/cloud-projects/pull/3977

Remove wrong CI "approval" check

---

.policy.yml

`Dockerfile.app` is used to create pre-defined Dockerfiles for
applications, Dependabot updates to these should require 1 reviewer.

Enable single review for bot update to Dockerfile.app

---

images/techdocs/context/mkdocs.yml

The [pymdownx.snippets][1] extension enables embedding of external
files. This is particular useful for diagrams and larger code examples.
[1]: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets

Add support for embedding files

---

docs/images/devtools-golang-v1beta1.md
images/devtools-golang-v1beta1/context/Dockerfile.app
images/devtools-golang-v1beta1/context/Makefile
images/devtools-golang-v1beta1/tests/test_image.py

The Golang devtools support the building of an OCI image for an application either from a devtool-supplied Dockerfile, or when significant customizations are required, a user-supplied Dockerfile.
To avoid unnecessary duplication of the supplied Dockerfile in the case where only a few additional resource files are needed, add support for copying a list of paths into the application's working directory.
This is an opinionated approach, however it should be possible to convert all remaining Go projects that supply their own Dockerfile to use the built in one either by using this feature alone, or with a little additional restructuring of env-specific things into ConfigMaps.

Support copying of additional resource files in devtool-supplied OCI image

---

images/devtools-terraform-v1beta1/context/Makefile
images/devtools-terraform-v1beta1/tests/test_image.py

`TFDIRS_EXCLUDE` was being ignored if `TFDIRS` was already set via env vars. 
This change makes sure that the excludes apply regardless of how `TFDIRS` is set. If the user wants to make sure that examples aren't excluded, it needs to be explicitly done by setting `TFDIRS_EXCLUDE`.
This change is related to the following issue: https://github.com/coopnorge/github-workflow-terraform-validation/issues/72

fix: Change how `TFDIRS_EXCLUDE` is interpreted

---

images/devtools-golang-v1beta1/context/Makefile

Disable Datadog WAF by default, as it now required some shared libraries to be present in the final docker-image.

build(golang): Disable Datadog WAF

---

images/devtools-golang-v1beta1/context/Dockerfile

Bullseye was released 14 August 2021, and has Security-EOL in July 2024.
Bookworm was released 10 June 2023, and har Security-EOL in June 2026.
https://en.wikipedia.org/wiki/Debian_version_history

chore: Bump Debian from Bullseye (11) to Bookworm (12)

---

images/techdocs/tests/test_image.py

There is no reason to lock markdownlint to a minor version. This just
causes friction when updating the image.

chore: Only validate against major version of markdownlint

---

docker-compose/Dockerfile

It seems this has not been updated in a while. The dependabot config looks correct, so I am assuming it's because of the gitc based tagging.

build(deps): Update techdocs image in Dockerfile

---

images/techdocs/context/Dockerfile

ref: https://github.com/coopnorge/engineering-docker-images/actions/runs/10034969048/job/27730300595

chore(deps): Update openjdk version in techdocs dockerfile to fix build failing

---

images/techdocs/context/Dockerfile

ci fails because the old version is no longer available in apt

chore: Update openjdk version

---

images/devtools-python3.10-v1beta1/context/Dockerfile.app

This is a devtool for python 3.10, it doesn't make sense to upgrade
the python version 3.13.
Reverting https://github.com/coopnorge/engineering-docker-images/pull/2241.

Revert "build(deps): bump python in /images/devtools-python3.10-v1beta1/context (#2241)"

---

images/devtools-terraform-v1beta1/context/Makefile

It seems that trivyignore is not working as expected (as we have tried to use in cloud-projects: https://github.com/coopnorge/cloud-projects/pull/5160). It expects `.trivyignore` in project root. We want to have it in the terraform directory (directories where the terraform files are).

fix: Use .trivyignore from the terraform directory being checked instead repo root

---

images/devtools-terraform-v1beta1/context/Makefile

This reverts commit 717826c16f700706546ebf9598e923add8871b22.
Undoing the workaround implemented here https://github.com/coopnorge/engineering-docker-images/pull/2269 because I realized that it doesn't actually solve our use-case. The workaround we need for config scanning is related to a different image (`ghcr.io/aquasecurity/trivy-checks:1`), which does not have an alternate mirror at this point (the mirror will be available if/when this is merged: https://github.com/aquasecurity/trivy-checks/pull/262)
ref: https://github.com/coopnorge/cloud-platform-team/issues/997

Revert "chore: Use workaround for trivy (#2269)"

---

images/devtools-terraform-v1beta1/context/Dockerfile
images/devtools-terraform-v1beta1/context/Makefile
images/devtools-terraform-v1beta1/tests/test_image.py

Also include and update manifest file.
ref: https://github.com/aquasecurity/trivy/blob/ed2288f1e7b1195db179191e51a1952272c2c064/pkg/policy/policy.go

fix: Correct directory for trivy cache

---

images/devtools-terraform-v1beta1/context/Makefile

Currently, local scans take a long time if a lot of files exist.

chore: Exclude node_modules, .git and .venv when scanning for tf dirs

---

images/devtools-golang-v1beta1/context/go.mod
images/devtools-golang-v1beta1/tests/prototype/go.mod
images/devtools-kubernetes-v1beta1/context/go.mod

failure in codeql run because of this: https://github.com/coopnorge/engineering-docker-images/security/code-scanning/tools/CodeQL/status/configurations/actions-FZTWS5DIOVRC653POJVWM3DPO5ZS643FMN2XE2LUPEWXGY3BNYXHSYLNNQ/bfbcc3db1f0fcfb6fac8a233c4d16a5b92b7e81c26ae172ec8129bcda9a245b2

fix: Use the full version in go directive

---

images/devtools-python3.10-v1beta1/context/Dockerfile

All version tags for crane are gone from the registry. Use `latest` as a
workaround.

fix: Use latest tag with digest for crane

---

images/devtools-golang-v1beta1/context/Makefile

* Was hard coded
* Conflicts with setting immutable tags on artifact repos
* Can be added by input of a workflow
* (And i personally i think we should move away from the concept of latest)

feat: disable hardcoded latest tag in image build

---

images/devtools-python3.10-v1beta1/context/Makefile

* disabled hardcoded tag
* allow user to set OCI_TAG_SUFFIX_USER to set a default tag
This allowed for now having the same tag always. This is required to
enable immuttable tags on OCI repos.

feat: disable hardcoded latest oci tag in python devtools and add user override

---

images/devtools-golang-v1beta1/context/Dockerfile.app
images/devtools-golang-v1beta1/context/Makefile

Implements linking source code to APM in Datadog.
See: https://app.datadoghq.eu/source-code/setup/apm

feat: golang - add api source code link in datadog

---

images/devtools-golang-v1beta1/context/Dockerfile.app

Moving to https://github.com/kvij/scuttle
reason:
This repo is a blatant copy and continuation of redboxllc/scuttle.
Unfortunately the original author/maintainer lost access and
redboxllc/scuttle is no longer maintained.

fix: update scuttle to a more up to date owner

---

docs/images/devtools-golang-v1beta1.md

It seems to have been mistakenly edited here: https://github.com/coopnorge/engineering-docker-images/pull/1248/files

docs: Fix the text in the golang-devtools docs

---

docs/images/devtools-golang-v1beta1.md
docs/images/devtools-terraform-v1beta1.md
docs/images/techdocs.md

* `devtools` directory is used instead of `docker-compose`
* `Dockerfile` is broken down into multiple files with each image in a different one
* `docker-compose.yaml` is also broken down into multiple files and included in the `docker-compose.yaml`
ref: https://github.com/coopnorge/backstage/tree/main/software-templates/generic-repository-template/template

docs: Align the documentation with the new template

---

images/techdocs/context/mkdocs.yml
images/techdocs/context/requirements-techdocs.in
images/techdocs/context/requirements-techdocs.txt
images/techdocs/tests/prototype/docs/index.md

This change adds support for GitHub style [alerts]. These serve the same
purpose as [admonitions] from Material for MkDocs, but also renders
correctly in pull requests on GitHub and allows works with [vale] for
spell checking.
Example:
```markdown
> [!NOTE]
> This is a note
```
Renders as
> [!NOTE]
> This is a note
[admonitions]: https://squidfunk.github.io/mkdocs-material/reference/admonitions/
[alerts]: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts
[vale]: https://vale.sh/

feat: Add support for GitHub style alerts in TechDocs

---

images/devtools-golang-v1beta1/context/.golangci.yml
images/devtools-golang-v1beta1/context/Dockerfile
images/devtools-golang-v1beta1/tests/prototype/main.go
images/devtools-golang-v1beta1/tests/test_image.py

This change upgrades Golangci-lint to version 2. With the upgrade brings
changes to several linters ([Full list of changes])
The most notable is the merge of the linters `stylecheck`, `gosimple`,
and `staticcheck` into `staticcheck`, the 3 linters all implement
https://staticcheck.dev/ rules.
The change causes the default rules from `stylecheck` to be active.
https://github.com/coopnorge/mage uses golangci-lint v2 with default
settings for static check. Initial testing of mage has detected violations of
[ST1005]: Incorrectly formatted error string. Further testing might
bring other violations to the surface.
The configuration was migrated using:
```console
golangci-lint migrate
```
Closes: https://github.com/coopnorge/engineering-issues/issues/444
[Full list of of changes]: …

chore(deps): Upgrade to golangci-lint v2

---

images/devtools-terraform-v1beta1/context/Dockerfile

Reverts coopnorge/engineering-docker-images#2688
Revert this because of issue
https://github.com/aquasecurity/trivy/issues/8805

Revert "build(deps): bump aquasec/trivy from 0.61.0 to 0.62.0 in /images/devtools-terraform-v1beta1/context"

---

images/devtools-kubernetes-v1beta1/context/Dockerfile

Same version as the server we use. 
It seems ArgoCD moved to quay some time ago: https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/1.8-2.0/#container-registry-switched-to-quayio-and-sundown-of-docker-hub-repository
ref: https://github.com/coopnorge/cloud-platform-team/issues/1058

chore: Use a later version of argoproj/argocd image

---

.github/dependabot.yml

We run 2.11
ref: https://github.com/coopnorge/engineering-docker-images/pull/2734
This change is relevant to this issue when we work on it: https://github.com/coopnorge/cloud-platform-team/issues/1058

chore: Restrict dependabot from updating argocd beyond v2.11

---

images/techdocs/context/Dockerfile
images/techdocs/tests/test_image.py

Change from vale binary from docker image to the one from releases because the one in docker images is now [compiled with CGO_ENABLED=1 on alpine](https://github.com/errata-ai/vale/commit/1a87d113f956796e6df6a9010ebe57e690680624) and is therefore not a standalone binary.
The latest version is 3.11.x, but it seems it may have additional requirements, so updating to 3.5 for now.
This means that dependabot updates will no longer work, and we may have to configure renovatebot at a later date.

chore: update vale to 3.5.0

---

images/techdocs/context/Makefile
images/techdocs/context/mkdocs.yml
images/techdocs/context/requirements-techdocs.in
images/techdocs/context/requirements-techdocs.txt
images/techdocs/tests/test_image.py

This changes adds the following metadata to each page
- list of contributors
- creation date

feat(techdocs): Add additional metadata

---

.github/renovate.json5
.github/workflows/renovate.yaml

Limiting to v3.8 for trying out how this works. I will remove the version limit later.
ref: https://github.com/coopnorge/engineering-docker-images/pull/2825

chore: Add renovate for vale version updates in techdocs Dockerfile

---

.github/renovate.json5

Also, migrate config version and remove version restriction.

fix: Correct regex string in renovate config for vale version updates

---

images/techdocs/context/Dockerfile

As discussed here, we are updating the vale version gradually: https://github.com/coopnorge/engineering-docker-images/pull/2825#issuecomment-3031749778

chore: Update vale to 3.8.0

---

images/techdocs/context/.prettierrc
images/techdocs/context/Dockerfile
images/techdocs/context/Makefile
images/techdocs/context/package-lock.json
images/techdocs/context/package.json

The TechDocs image does not have a formatter, but a very strict linting of formatting rules (like a max length of 80 characters per line). This PR adds a standardized formatter [Prettier](https://prettier.io/) to the tooling, **without** running it as part of `validate` and `validate-fix` yet. This will let us be able to run the formatter on a couple repos, to assess better if there are any major conflicts between Prettier and Markdownlint that needs to be resolved.
Part of #3054

feat(techdocs): Add Prettier as formatter for markdown files
